"""init schema

Revision ID: 51e22ab7d9b4
Revises:
Create Date: 2026-08-14 09:10:29.935340

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51e22ab7d9b4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sys_client",
        sa.Column("client_id", sa.String(length=64), nullable=True, comment="客户端id"),
        sa.Column("client_key", sa.String(length=32), nullable=True, comment="客户端key"),
        sa.Column("client_secret", sa.String(length=255), nullable=True, comment="客户端秘钥"),
        sa.Column("grant_type", sa.String(length=255), nullable=True, comment="授权类型（逗号分隔）"),
        sa.Column("device_type", sa.String(length=32), nullable=True, comment="设备类型"),
        sa.Column("active_timeout", sa.Integer(), nullable=True, comment="token活跃超时时间（秒）"),
        sa.Column("timeout", sa.Integer(), nullable=True, comment="token固定超时时间（秒）"),
        sa.Column("status", sa.String(length=1), nullable=True, comment="状态（0正常 1停用）"),
        sa.Column("del_flag", sa.String(length=1), nullable=False, comment="删除标志（0代表存在 1代表删除）"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_client")),
        comment="系统授权表",
    )
    op.create_index(op.f("ix_sys_client_del_flag"), "sys_client", ["del_flag"], unique=False)
    op.create_table(
        "sys_config",
        sa.Column("config_name", sa.String(length=100), nullable=True, comment="参数名称"),
        sa.Column("config_key", sa.String(length=100), nullable=True, comment="参数键名"),
        sa.Column("config_value", sa.String(length=500), nullable=True, comment="参数键值"),
        sa.Column("config_type", sa.String(length=1), nullable=True, comment="系统内置（Y是 N否）"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_config")),
        comment="参数配置表",
    )
    op.create_index(op.f("ix_sys_config_config_key"), "sys_config", ["config_key"], unique=False)
    op.create_table(
        "sys_dept",
        sa.Column("parent_id", sa.BigInteger(), nullable=True, comment="父部门ID"),
        sa.Column("ancestors", sa.String(length=500), nullable=True, comment="祖级列表"),
        sa.Column("dept_name", sa.String(length=30), nullable=True, comment="部门名称"),
        sa.Column("dept_category", sa.String(length=100), nullable=True, comment="部门类别编码"),
        sa.Column("order_num", sa.Integer(), nullable=True, comment="显示顺序"),
        sa.Column("leader", sa.BigInteger(), nullable=True, comment="负责人（用户ID）"),
        sa.Column("phone", sa.String(length=11), nullable=True, comment="联系电话"),
        sa.Column("email", sa.String(length=50), nullable=True, comment="邮箱"),
        sa.Column("status", sa.String(length=1), nullable=True, comment="部门状态（0正常 1停用）"),
        sa.Column("del_flag", sa.String(length=1), nullable=False, comment="删除标志（0代表存在 1代表删除）"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_dept")),
        comment="部门表",
    )
    op.create_index(op.f("ix_sys_dept_del_flag"), "sys_dept", ["del_flag"], unique=False)
    op.create_index(op.f("ix_sys_dept_parent_id"), "sys_dept", ["parent_id"], unique=False)
    op.create_table(
        "sys_dict_data",
        sa.Column("dict_sort", sa.Integer(), nullable=True, comment="字典排序"),
        sa.Column("dict_label", sa.String(length=100), nullable=True, comment="字典标签"),
        sa.Column("dict_value", sa.String(length=100), nullable=True, comment="字典键值"),
        sa.Column("dict_type", sa.String(length=100), nullable=True, comment="字典类型"),
        sa.Column("css_class", sa.String(length=100), nullable=True, comment="样式属性（其他样式扩展）"),
        sa.Column("list_class", sa.String(length=100), nullable=True, comment="表格回显样式"),
        sa.Column("is_default", sa.String(length=1), nullable=True, comment="是否默认（Y是 N否）"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_dict_data")),
        comment="字典数据表",
    )
    op.create_index(op.f("ix_sys_dict_data_dict_type"), "sys_dict_data", ["dict_type"], unique=False)
    op.create_table(
        "sys_dict_type",
        sa.Column("dict_name", sa.String(length=100), nullable=True, comment="字典名称"),
        sa.Column("dict_type", sa.String(length=100), nullable=True, comment="字典类型"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_dict_type")),
        sa.UniqueConstraint("dict_type", name=op.f("uq_sys_dict_type_dict_type")),
        comment="字典类型表",
    )
    op.create_table(
        "sys_logininfor",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="访问ID（雪花）"),
        sa.Column("user_name", sa.String(length=50), nullable=True, comment="用户账号"),
        sa.Column("client_key", sa.String(length=32), nullable=True, comment="客户端"),
        sa.Column("device_type", sa.String(length=32), nullable=True, comment="设备类型"),
        sa.Column("ipaddr", sa.String(length=128), nullable=True, comment="登录IP地址"),
        sa.Column("login_location", sa.String(length=255), nullable=True, comment="登录地点"),
        sa.Column("browser", sa.String(length=50), nullable=True, comment="浏览器类型"),
        sa.Column("os", sa.String(length=50), nullable=True, comment="操作系统"),
        sa.Column("status", sa.String(length=1), nullable=True, comment="登录状态（0成功 1失败）"),
        sa.Column("msg", sa.String(length=255), nullable=True, comment="提示消息"),
        sa.Column("login_time", sa.DateTime(), nullable=True, comment="访问时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_logininfor")),
        comment="系统访问记录",
    )
    op.create_index(op.f("ix_sys_logininfor_login_time"), "sys_logininfor", ["login_time"], unique=False)
    op.create_index(op.f("ix_sys_logininfor_status"), "sys_logininfor", ["status"], unique=False)
    op.create_table(
        "sys_menu",
        sa.Column("menu_name", sa.String(length=50), nullable=False, comment="菜单名称"),
        sa.Column("parent_id", sa.BigInteger(), nullable=True, comment="父菜单ID"),
        sa.Column("order_num", sa.Integer(), nullable=True, comment="显示顺序"),
        sa.Column("path", sa.String(length=200), nullable=True, comment="路由地址"),
        sa.Column("component", sa.String(length=255), nullable=True, comment="组件路径"),
        sa.Column("query_param", sa.String(length=255), nullable=True, comment="路由参数"),
        sa.Column("is_frame", sa.String(length=1), nullable=True, comment="是否为外链（0是 1否）"),
        sa.Column("is_cache", sa.String(length=1), nullable=True, comment="是否缓存（0缓存 1不缓存）"),
        sa.Column("menu_type", sa.String(length=1), nullable=True, comment="菜单类型（M目录 C菜单 F按钮）"),
        sa.Column("visible", sa.String(length=1), nullable=True, comment="显示状态（0显示 1隐藏）"),
        sa.Column("status", sa.String(length=1), nullable=True, comment="菜单状态（0正常 1停用）"),
        sa.Column("perms", sa.String(length=100), nullable=True, comment="权限标识"),
        sa.Column("icon", sa.String(length=100), nullable=True, comment="菜单图标"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_menu")),
        comment="菜单权限表",
    )
    op.create_index(op.f("ix_sys_menu_parent_id"), "sys_menu", ["parent_id"], unique=False)
    op.create_table(
        "sys_notice",
        sa.Column("notice_title", sa.String(length=50), nullable=False, comment="公告标题"),
        sa.Column("notice_type", sa.String(length=1), nullable=False, comment="公告类型（1通知 2公告）"),
        sa.Column("notice_content", sa.LargeBinary(), nullable=True, comment="公告内容（UTF-8 字节）"),
        sa.Column("status", sa.String(length=1), nullable=True, comment="公告状态（0正常 1关闭）"),
        sa.Column("remark", sa.String(length=255), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_notice")),
        comment="通知公告表",
    )
    op.create_table(
        "sys_oper_log",
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="日志主键（雪花）"),
        sa.Column("title", sa.String(length=50), nullable=True, comment="模块标题"),
        sa.Column("business_type", sa.Integer(), nullable=True, comment="业务类型（0其它 1新增 2修改 3删除）"),
        sa.Column("method", sa.String(length=100), nullable=True, comment="方法名称"),
        sa.Column("request_method", sa.String(length=10), nullable=True, comment="请求方式"),
        sa.Column("operator_type", sa.Integer(), nullable=True, comment="操作类别（0其它 1后台用户 2手机端用户）"),
        sa.Column("oper_name", sa.String(length=50), nullable=True, comment="操作人员"),
        sa.Column("dept_name", sa.String(length=50), nullable=True, comment="部门名称"),
        sa.Column("oper_url", sa.String(length=255), nullable=True, comment="请求URL"),
        sa.Column("oper_ip", sa.String(length=128), nullable=True, comment="主机地址"),
        sa.Column("oper_location", sa.String(length=255), nullable=True, comment="操作地点"),
        sa.Column("oper_param", sa.String(length=4000), nullable=True, comment="请求参数"),
        sa.Column("json_result", sa.String(length=4000), nullable=True, comment="返回参数"),
        sa.Column("status", sa.Integer(), nullable=True, comment="操作状态（0正常 1异常）"),
        sa.Column("error_msg", sa.String(length=4000), nullable=True, comment="错误消息"),
        sa.Column("oper_time", sa.DateTime(), nullable=True, comment="操作时间"),
        sa.Column("cost_time", sa.BigInteger(), nullable=True, comment="消耗时间（毫秒）"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_oper_log")),
        comment="操作日志记录",
    )
    op.create_index(op.f("ix_sys_oper_log_business_type"), "sys_oper_log", ["business_type"], unique=False)
    op.create_index(op.f("ix_sys_oper_log_oper_time"), "sys_oper_log", ["oper_time"], unique=False)
    op.create_index(op.f("ix_sys_oper_log_status"), "sys_oper_log", ["status"], unique=False)
    op.create_index(op.f("ix_sys_oper_log_title"), "sys_oper_log", ["title"], unique=False)
    op.create_table(
        "sys_post",
        sa.Column("dept_id", sa.BigInteger(), nullable=False, comment="部门ID"),
        sa.Column("post_code", sa.String(length=64), nullable=False, comment="岗位编码"),
        sa.Column("post_category", sa.String(length=100), nullable=True, comment="岗位类别编码"),
        sa.Column("post_name", sa.String(length=50), nullable=False, comment="岗位名称"),
        sa.Column("post_sort", sa.Integer(), nullable=False, comment="显示顺序"),
        sa.Column("status", sa.String(length=1), nullable=False, comment="状态（0正常 1停用）"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_post")),
        comment="岗位信息表",
    )
    op.create_table(
        "sys_role",
        sa.Column("role_name", sa.String(length=30), nullable=False, comment="角色名称"),
        sa.Column("role_key", sa.String(length=100), nullable=False, comment="角色权限字符串"),
        sa.Column("role_sort", sa.Integer(), nullable=False, comment="显示顺序"),
        sa.Column("data_scope", sa.String(length=1), nullable=True, comment="数据范围（1全部 2自定义 3本部门 4本部门及以下 5仅本人 6本部门及以下或本人）"),
        sa.Column("menu_check_strictly", sa.Integer(), nullable=True, comment="菜单树选择项是否关联显示"),
        sa.Column("dept_check_strictly", sa.Integer(), nullable=True, comment="部门树选择项是否关联显示"),
        sa.Column("status", sa.String(length=1), nullable=False, comment="角色状态（0正常 1停用）"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("del_flag", sa.String(length=1), nullable=False, comment="删除标志（0代表存在 1代表删除）"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_role")),
        comment="角色信息表",
    )
    op.create_index(op.f("ix_sys_role_del_flag"), "sys_role", ["del_flag"], unique=False)
    op.create_table(
        "sys_role_dept",
        sa.Column("role_id", sa.BigInteger(), nullable=False, comment="角色ID"),
        sa.Column("dept_id", sa.BigInteger(), nullable=False, comment="部门ID"),
        sa.PrimaryKeyConstraint("role_id", "dept_id", name=op.f("pk_sys_role_dept")),
        comment="角色和部门关联表",
    )
    op.create_table(
        "sys_role_menu",
        sa.Column("role_id", sa.BigInteger(), nullable=False, comment="角色ID"),
        sa.Column("menu_id", sa.BigInteger(), nullable=False, comment="菜单ID"),
        sa.PrimaryKeyConstraint("role_id", "menu_id", name=op.f("pk_sys_role_menu")),
        comment="角色和菜单关联表",
    )
    op.create_table(
        "sys_social",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("auth_id", sa.String(length=255), nullable=False, comment="平台+平台唯一id"),
        sa.Column("source", sa.String(length=255), nullable=False, comment="用户来源"),
        sa.Column("open_id", sa.String(length=255), nullable=True, comment="平台openid"),
        sa.Column("user_name", sa.String(length=30), nullable=False, comment="登录账号"),
        sa.Column("nick_name", sa.String(length=30), nullable=True, comment="用户昵称"),
        sa.Column("email", sa.String(length=255), nullable=True, comment="用户邮箱"),
        sa.Column("avatar", sa.String(length=500), nullable=True, comment="用户头像"),
        sa.Column("access_token", sa.String(length=2000), nullable=False, comment="用户的授权令牌"),
        sa.Column("expire_in", sa.Integer(), nullable=True, comment="access_token的过期时间"),
        sa.Column("refresh_token", sa.String(length=255), nullable=True, comment="刷新令牌"),
        sa.Column("access_code", sa.String(length=2000), nullable=True, comment="授权code"),
        sa.Column("union_id", sa.String(length=255), nullable=True, comment="平台union_id"),
        sa.Column("scope", sa.String(length=255), nullable=True, comment="授予的权限"),
        sa.Column("token_type", sa.String(length=255), nullable=True, comment="令牌类型"),
        sa.Column("id_token", sa.String(length=2000), nullable=True, comment="id_token(部分平台可用)"),
        sa.Column("mac_algorithm", sa.String(length=255), nullable=True, comment="MAC算法"),
        sa.Column("mac_key", sa.String(length=255), nullable=True, comment="MAC密钥"),
        sa.Column("code", sa.String(length=255), nullable=True, comment="请求码"),
        sa.Column("oauth_token", sa.String(length=255), nullable=True, comment="OAuth token"),
        sa.Column("oauth_token_secret", sa.String(length=255), nullable=True, comment="OAuth token secret"),
        sa.Column("del_flag", sa.String(length=1), nullable=False, comment="删除标志（0代表存在 1代表删除）"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_social")),
        comment="社交授权关系表",
    )
    op.create_index(op.f("ix_sys_social_del_flag"), "sys_social", ["del_flag"], unique=False)
    op.create_index(op.f("ix_sys_social_user_id"), "sys_social", ["user_id"], unique=False)
    op.create_table(
        "sys_user",
        sa.Column("dept_id", sa.BigInteger(), nullable=True, comment="部门ID"),
        sa.Column("user_name", sa.String(length=30), nullable=False, comment="用户账号"),
        sa.Column("nick_name", sa.String(length=30), nullable=False, comment="用户昵称"),
        sa.Column("user_type", sa.String(length=10), nullable=False, comment="用户类型（sys_user系统用户）"),
        sa.Column("email", sa.String(length=50), nullable=True, comment="用户邮箱"),
        sa.Column("phonenumber", sa.String(length=11), nullable=True, comment="手机号码"),
        sa.Column("sex", sa.String(length=1), nullable=True, comment="用户性别"),
        sa.Column("avatar", sa.String(length=500), nullable=True, comment="用户头像"),
        sa.Column("password", sa.String(length=100), nullable=True, comment="密码"),
        sa.Column("status", sa.String(length=1), nullable=False, comment="帐号状态（0正常 1停用）"),
        sa.Column("login_ip", sa.String(length=128), nullable=True, comment="最后登录IP"),
        sa.Column("login_date", sa.DateTime(), nullable=True, comment="最后登录时间"),
        sa.Column("remark", sa.String(length=500), nullable=True, comment="备注"),
        sa.Column("del_flag", sa.String(length=1), nullable=False, comment="删除标志（0代表存在 1代表删除）"),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False, comment="主键ID（雪花）"),
        sa.Column("create_dept", sa.BigInteger(), nullable=True, comment="创建部门"),
        sa.Column("create_by", sa.BigInteger(), nullable=True, comment="创建者"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_by", sa.BigInteger(), nullable=True, comment="更新者"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sys_user")),
        comment="用户信息表",
    )
    op.create_index(op.f("ix_sys_user_del_flag"), "sys_user", ["del_flag"], unique=False)
    op.create_index(op.f("ix_sys_user_dept_id"), "sys_user", ["dept_id"], unique=False)
    op.create_index(op.f("ix_sys_user_user_name"), "sys_user", ["user_name"], unique=False)
    op.create_table(
        "sys_user_post",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("post_id", sa.BigInteger(), nullable=False, comment="岗位ID"),
        sa.PrimaryKeyConstraint("user_id", "post_id", name=op.f("pk_sys_user_post")),
        comment="用户与岗位关联表",
    )
    op.create_table(
        "sys_user_role",
        sa.Column("user_id", sa.BigInteger(), nullable=False, comment="用户ID"),
        sa.Column("role_id", sa.BigInteger(), nullable=False, comment="角色ID"),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_sys_user_role")),
        comment="用户和角色关联表",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sys_user_role")
    op.drop_table("sys_user_post")
    op.drop_index(op.f("ix_sys_user_user_name"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_dept_id"), table_name="sys_user")
    op.drop_index(op.f("ix_sys_user_del_flag"), table_name="sys_user")
    op.drop_table("sys_user")
    op.drop_index(op.f("ix_sys_social_user_id"), table_name="sys_social")
    op.drop_index(op.f("ix_sys_social_del_flag"), table_name="sys_social")
    op.drop_table("sys_social")
    op.drop_table("sys_role_menu")
    op.drop_table("sys_role_dept")
    op.drop_index(op.f("ix_sys_role_del_flag"), table_name="sys_role")
    op.drop_table("sys_role")
    op.drop_table("sys_post")
    op.drop_index(op.f("ix_sys_oper_log_title"), table_name="sys_oper_log")
    op.drop_index(op.f("ix_sys_oper_log_status"), table_name="sys_oper_log")
    op.drop_index(op.f("ix_sys_oper_log_oper_time"), table_name="sys_oper_log")
    op.drop_index(op.f("ix_sys_oper_log_business_type"), table_name="sys_oper_log")
    op.drop_table("sys_oper_log")
    op.drop_table("sys_notice")
    op.drop_index(op.f("ix_sys_menu_parent_id"), table_name="sys_menu")
    op.drop_table("sys_menu")
    op.drop_index(op.f("ix_sys_logininfor_status"), table_name="sys_logininfor")
    op.drop_index(op.f("ix_sys_logininfor_login_time"), table_name="sys_logininfor")
    op.drop_table("sys_logininfor")
    op.drop_table("sys_dict_type")
    op.drop_index(op.f("ix_sys_dict_data_dict_type"), table_name="sys_dict_data")
    op.drop_table("sys_dict_data")
    op.drop_index(op.f("ix_sys_dept_parent_id"), table_name="sys_dept")
    op.drop_index(op.f("ix_sys_dept_del_flag"), table_name="sys_dept")
    op.drop_table("sys_dept")
    op.drop_index(op.f("ix_sys_config_config_key"), table_name="sys_config")
    op.drop_table("sys_config")
    op.drop_index(op.f("ix_sys_client_del_flag"), table_name="sys_client")
    op.drop_table("sys_client")
    # ### end Alembic commands ###
